### ISSUE TITLE
spark shows that the mod is laggy with the `yeetUpdateSuppressionCrash_implOnTickWorlds` method

### ISSUE THREAD

**Issue by MrPacha23** [TISUnion/Carpet-TIS-Addition#136] opened 2024-01-27 02:13 UTC
### Bug description

Hello, I have been having problems on my server with the TPS and the MSPT, it is very laggy on some occasions, I have consulted the technicians at the server host and they have made me run a spark test and they have found the problem that This is being the mod. I am attaching the link of the problem that spark is launching so that you can verify it and see what solution can be given. I ran 3 tests, I attach all of them.

First test: https://spark.lucko.me/djKU5R6nZw
Second test: https://spark.lucko.me/1v3PAGdEQD
Third test: https://spark.lucko.me/iOmrZqp32C

### Steps to reproduce

Every so often

### Expected behavior

Let it go correctly

### Actual behavior

It's laggy

### Relevant logs

First test: https://spark.lucko.me/djKU5R6nZw
Second test: https://spark.lucko.me/1v3PAGdEQD
Third test: https://spark.lucko.me/iOmrZqp32C

### Minecraft version

1.20.4

### Carpet TIS Addition version

1.55.0

### Fabric Carpet version

1.4.128

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment] 2024-01-27 05:16
duplicate of #118. unrelated to this mod

**Comment by Fallen-Breath** [comment] 2024-01-27 05:29
In case it's hard for you to read https://github.com/TISUnion/Carpet-TIS-Addition/issues/118 which is in Chinese, here's the explaination in English:

`yeetUpdateSuppressionCrash_implOnTickWorlds` is a wrapper function of the `ServerWorld#tick` method, and the latter one is what the world ticking logic of Minecraft is in, which of course takes a lot of times and seems to be "laggy"

You can verify this by:

1. Inspect the profile tree
![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/28978806/4f070259-a32b-4d70-b32c-09c345fc7277)

2. Check the flame graph feature
![image](https://github.com/TISUnion/Carpet-TIS-Addition/assets/28978806/6795bfe8-218d-4e46-a382-310388cb6743)

**Closed as not planned by Fallen-Breath** 2024-01-27 05:29 UTC
Labels: duplicate

**Comment by MrPacha23** [comment] 2024-01-27 05:32
Thank you so much

**Comment by kspubg** [comment] 2025-04-21 12:43
我也有此问题，我是Java1.20.1fabric服https://spark.lucko.me/OtCap3MzrG

**Comment by Fallen-Breath** [comment] 2025-04-21 14:45
> 我也有此问题，我是Java1.20.1fabric服https://spark.lucko.me/OtCap3MzrG

本 issue 的评论里已经说清楚了，所谓类似的”问题“实则均为用户对 spark 性能分析结果的错误分析，均与本 mod 无关，本 mod 并未造成任何额外卡顿

**Comment by kspubg** [comment] 2025-04-21 15:01
> > 我也有这个问题，我是Java1.20.1fabric服https://spark.lucko.me/OtCap3MzrG
> 
> 本问题 的评论里已经说清楚了，所谓类似的”问题“实则均用户对火花性能分析结果的错误分析，均与本模无关，本模并未造成任何额外卡顿

好的，我已知晓，谢谢你
