### ISSUE TITLE
Incompability with carpet shadow and tis 1.53.1

### ISSUE THREAD

**Issue by Rozbiynk** [TISUnion/Carpet-TIS-Addition#121] opened 2023-11-11 07:28 UTC
### Bug description

If carpet shadow installed, carpet tis addition 1.53.1 lead to crash

### Steps to reproduce

1. Install carpet shadow 1.10.2
2. install carpet 1.4.112
3. install tis addition 1.53.1
4. launch game
5. crash

### Expected behavior

launch game

### Actual behavior

game crashes

### Relevant logs

https://mclo.gs/xQNWpkR

### Minecraft version

1.20.1

### Carpet TIS Addition version

1.53.1

### Fabric Carpet version

1.4.112

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment] 2023-11-11 15:06
I guess the cause is that carpet-shadow ships MixinExtras wrongly. Possible reasons:

- It shades MixinExtras, but does not relocate the MixinExtras. very sus
- The game crashes in production environment, but works fine fine in dev environment
- The crash report says mixin on class `ReentrantThreadExecutor` fails, but only carpet-tis-addition mixins into that class, carpet-shadow doesn't. So it's not a mixin confliction

I'll suggest to report this issue to carpet-shadow

**Comment by mattymatty97** [comment] 2023-11-11 16:50
it probably comes form me bundling MixinExtras incorrectly as i noticed in another mod i maintain.. it indeed does work in dev as my dev environment actually has TIS addition too 😅 .
i will push a new fixed release soon. and see if i can replicate the incompatibility

**Comment by Fallen-Breath** [comment] 2024-02-12 15:22
Closed as the related issue on carpet-shadow is closed

**Closed as completed by Fallen-Breath** 2024-02-12 15:22 UTC
Labels: compatibility, external issue
